### ISSUE TITLE
Missing Vessel of the Dragon

### ISSUE THREAD

**Issue by blueyu2** [BeetoGuy/BetterWithMods#193]
The Vessel of the Dragon is currently missing from the Jungle Temple.

I'm currently working on adding it, but for whatever reason Immersive Engineering has all Minecraft fields and methods obfuscated in its code, where it has `if(!world.field_72995_K)` instead of `if(!world.isRemote)`. As a result, I cannot launch the game to test the vessel.

Until I can find a solution to IE, I'll do what I can with the vessel and submit a PR so someone with a working dev workspace can test it.

**Comment by primetoxinz** [comment]
that commit should fix that

**Comment by blueyu2** [comment]
Thank you, but IE is still having issues. I'll just do what I can and submit a PR for testing the vessel.

**Comment by primetoxinz** [comment]
that should have definitely fixed it, you can always comment out the IE dependency and re-setup then exclude the IE module
